/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteSuporteRouteImport } from './routes/cliente/suporte'
import { Route as ClientePlayerRouteImport } from './routes/cliente/player'
import { Route as ClientePerfilRouteImport } from './routes/cliente/perfil'
import { Route as ClienteDashboardRouteImport } from './routes/cliente/dashboard'

const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteSuporteRoute = ClienteSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePlayerRoute = ClientePlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteDashboardRoute = ClienteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClienteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/player': typeof ClientePlayerRoute
  '/cliente/suporte': typeof ClienteSuporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/player': typeof ClientePlayerRoute
  '/cliente/suporte': typeof ClienteSuporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/cliente/player': typeof ClientePlayerRoute
  '/cliente/suporte': typeof ClienteSuporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/cliente/dashboard'
    | '/cliente/perfil'
    | '/cliente/player'
    | '/cliente/suporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/cliente/dashboard'
    | '/cliente/perfil'
    | '/cliente/player'
    | '/cliente/suporte'
  id:
    | '__root__'
    | '/'
    | '/cliente'
    | '/cliente/dashboard'
    | '/cliente/perfil'
    | '/cliente/player'
    | '/cliente/suporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/suporte': {
      id: '/cliente/suporte'
      path: '/suporte'
      fullPath: '/cliente/suporte'
      preLoaderRoute: typeof ClienteSuporteRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/player': {
      id: '/cliente/player'
      path: '/player'
      fullPath: '/cliente/player'
      preLoaderRoute: typeof ClientePlayerRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/dashboard': {
      id: '/cliente/dashboard'
      path: '/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof ClienteDashboardRouteImport
      parentRoute: typeof ClienteRoute
    }
  }
}

interface ClienteRouteChildren {
  ClienteDashboardRoute: typeof ClienteDashboardRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClientePlayerRoute: typeof ClientePlayerRoute
  ClienteSuporteRoute: typeof ClienteSuporteRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteDashboardRoute: ClienteDashboardRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClientePlayerRoute: ClientePlayerRoute,
  ClienteSuporteRoute: ClienteSuporteRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
